name: Publish Obsidian Notes

on:
  push:
    branches:
      - vault

permissions:
  contents: write

jobs:
  publish:

    if: github.actor != 'github-actions[bot]'

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          ref: vault

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Convert Markdown
        run: |
          python obsidian-to-github-md.py

      ########################################################

      - name: Checkout Deploy Branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: deploy
          fetch-depth: 1

      ########################################################

      - name: Sync Published Files
        run: |

          rsync -a --delete .temp_publish/Published/ deploy/Published/

      ########################################################

      - name: Commit and Push Published Content
        working-directory: deploy
        run: |

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .

          if git diff --cached --quiet; then
            echo "No changes to publish."
            exit 0
          fi

          git commit -m "${{ github.event.head_commit.message }}"

          git push origin main

      ########################################################

      - name: Checkout Portfolio
        uses: actions/checkout@v4
        with:
          repository: grapeve12/my-portfolio-site
          token: ${{ secrets.PORTFOLIO_REPO_TOKEN }}
          ref: main
          path: portfolio
          submodules: true
          fetch-depth: 1

      ########################################################

      - name: Update Obsidian Submodule
        working-directory: portfolio
        run: |
          git submodule update --remote content/obsidian

      ########################################################

      - name: Commit and Push Portfolio
        working-directory: portfolio
        run: |

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add content/obsidian

          if git diff --cached --quiet; then
            echo "No submodule changes."
            exit 0
          fi

          git commit -m "chore: update obsidian content"

          git push origin main